Flight
wesolyigor/air_reservation_system pull request #1
Opened 2020-02-28 16:01 UTC by wesolyigor

review pls

2020-02-28 17:15 UTC, pawelkonior requested changes

2020-02-28 17:15 UTC, pawelkonior commented on air_reservation_system.py
> +
tu są 2

2020-02-28 17:16 UTC, pawelkonior commented on README.MD
>  #Air Reservation System
po # ma być spacja

2020-02-28 17:20 UTC, adkubaty commented
flight powinien byc zmergowany do mastera, prosze popraw

2020-02-28 17:21 UTC, adkubaty requested changes
branch flight musi byc zmergowany do mastera a nie do nowybranch

2020-02-29 15:10 UTC, closed without merging

2020-02-29 15:22 UTC, wesolyigor commented on README.MD
>  #Air Reservation System
Done

2020-02-29 15:22 UTC, wesolyigor commented
done

2020-02-29 15:24 UTC, wesolyigor commented on air_reservation_system.py
> +
done